[tasks.watch]
workspace = false
command = "cargo"
args = ["watch", "-x", "run", "-w", "crates"]

[tasks.docker-build]
workspace = false
command = "docker"
args = ["buildx", "build", "--platform=linux/amd64,linux/arm64", "-t", "movingju/public:o_log_n", "."]

[tasks.docker-push]
workspace = false
command = "docker"
args = ["push", "movingju/public:o_log_n"]